### ISSUE TITLE
完善track_util & midi_util

### ISSUE THREAD

**Issue by dmyang42** [FrendoWu/beats2beats#5]
RT

**Comment by ppzqh** [comment]
1. midi_util: 
- gen_multitracks中添加了打击乐的情况。
- 添加了tempo函数

2. track_util：
- 在matrix中添加了tempo, channel, program，调整几个函数。
- 修改change_program，添加了打击乐的情况

**Comment by dmyang42** [comment]
那怎么不PR 你好坏

**Comment by dmyang42** [comment]
#6
